config/routes.rb
Rails.application.routes.draw do
  # get 'docs/index'
  
  # get "/", to: "docs#index"
  # get "/docs/:id", to: "docs#show"
  # root "docs#index"
  # # get "/docs/:id/edit", to: "docs#edit"
  # resources :docs
  # resources :doc do
  #   resources :comments
  # end
  resources :docs
  get "/", to: "user#signin"
  post 'register', to: 'user#create', as: 'register'
  get "/login", to: "user#login"
  post "login", to: "user#login"  
  get 'docs/index', to: 'docs#index', as: 'index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :content, presence: true 
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :docs, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authenticate_user!
    redirect_to login_path, alert: "You need to sign in first" unless current_user
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @blogs = Blog.all
  end

  # def show
  #   @blog = Blog.find(params[:id])
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @doc = Article.find(params[:doc_id])
    @comment = @doc.comments.create(comment_params)
    redirect_to doc_path(@doc)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :authenticate_user!
  # def index
  #   @docs = Doc.all
  # end

  # def show
  #   @doc = Doc.find(params[:id])
  # end
  def index
    @docs = current_user.docs  # Show only the docs that belong to the logged-in user
  end

  def show
    @doc = Doc.find(params[:id])
  end

  def new
    @doc = Doc.new
  end

  def create
    @doc = current_user.docs.build(doc_params)  # Associate the doc with the logged-in user

    if @doc.save
      redirect_to @doc, notice: 'Doc was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @doc = Doc.find(params[:id])
  end

  def update
    @doc = Doc.find(params[:id])

    if @doc.update(doc_params)
      redirect_to @doc
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy

    redirect_to docs_path, status: :see_other
  end

  private
    def doc_params
      params.require(:doc).permit(:title, :body)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def signin
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if User.exists?(email: user_params[:email])
      flash.now[:alert] = "Email already exists"
      render :signin, status: :unprocessable_entity
    elsif @user.save
      redirect_to login_path, notice: 'Signin was successfully created.'
    else
      render :signin, status: :unprocessable_entity
    end
  end
  
  def login
    if request.post?
      email = params[:email]
      password = params[:password]
  
      @user = User.find_by(email: email)
      if @user&.authenticate(password)
        session[:user_id] = @user.id
        redirect_to docs_path, notice: "Logged in successfully"  # Correct path
      else
        flash.now[:alert] = "Invalid email or password"
        render :login, status: :unprocessable_entity
      end
    end
  end
  

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/blog/index.html.erb
<h1>Articles</h1>

<ul>
  <% @blogs.each do |blog| %>
    <li>
      <%= blog.title %>
    </li>
  <% end %>
</ul>

app/views/blog/show.html.erb
<h1><%= @blogs.title %></h1>

<p><%= @blogs.body %></p>

app/views/docs/_form.html.erb
<%= form_with model: doc do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% doc.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% doc.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", doc: @doc %>

app/views/docs/index.html.erb
<ul>
  <% @docs.each do |doc| %>
    <li>
    <%= link_to doc.title, doc %>
      </a>
    </li>
    <%end%>
</ul>

<%= link_to "New Doc", new_doc_path %>

app/views/docs/new.html.erb
<h1>New doc</h1>

<%= form_with model: @doc do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @doc.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @doc.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/docs/show.html.erb
<h1><%= @doc.title %></h1>

<p><%= @doc.body %></p>

<ul>
  <li><%= link_to "Edit", edit_doc_path(@doc) %></li>
  <li><%= link_to "Destroy", doc_path(@doc), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<%= link_to "Doc page", docs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyBlogs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/login.html.erb
 <div class="container">
  <div class="card2 register">
  <h2>Login</h2>
<%= form_with url: login_path, method: :post do |form| %>
  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </div>

  <div class = "fsub">
    <%= form.submit "Login"%>
  </div>
<% end %>
</div>
</div>

app/views/user/signin.html.erb
<h2>Register</h2>
<%= form_with model: @user, url: register_path, method: :post do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </div>

  <div class="fsub">
    <%= form.submit 'Register' %>
  </div>
<% end %>